### ISSUE TITLE
Certain folders will freeze after opening

### ISSUE THREAD

**Issue by murrty** [chishm/nitrohax#10]
I've narrowed it down to this line

https://github.com/chishm/nitrohax/blob/3781957b1a62ece91b100003e1a2cb78eb321509/arm9/source/ui.cpp#L657

Changing "contents[menuLevel.selected]->getName()" to a generic string will fix the issue, however, since I only have one flashcart, I can't say for sure if the problem is just because of my flashcart. It seems to stem from trying to read the item name but it confuses itself on the parent folder.

**Comment by murrty** [comment]
If anyone with a flashcart reads this and wants to test it, here's a build that has fixed it for me, the more confirmed cases of the issue the better, i guess.

[NitroHax.zip](https://github.com/chishm/nitrohax/files/4172307/NitroHax.zip)

however, it's graphically different from chishm's

**Comment by chishm** [comment]
Can you please post the XML file with the bad folder name? It might help with the debugging.

**Comment by murrty** [comment]
[Pokemon_Platinum.zip](https://github.com/chishm/nitrohax/files/4177272/Pokemon_Platinum.zip)

The folders that don't properly work are

> Alternative WFC
Game Time Codes
Check/View Stats Codes
Money Codes
Trainer Gender Modifier Codes
Pokemon Related
Chances of Encounter Codes
Underground Item Codes
Battle Spiritomb at Hallowed Tower Codes
Movement Codes
Safari Zone Codes
Weather Modifier
Character Modifier
Union/Wifi Room Character Modifier
Wifi Arena Background Modifier

there's probably more but those are ones that do not work.

**Comment by murrty** [comment]
I recently got an r4i gold plus, and when I tested it it ended up not working for any folder. I looked at #11 and it did seem to fix the problem on the gold, and also on the sdhc cart where some folders crashed.

**Comment by chishm** [comment]
Thank you for testing the patch and confirming that it works. I've merged it now, so I think that means this issue is closed.
