### ISSUE TITLE
 Golden Sun: Dark Dawn unsupported

### ISSUE THREAD

**Issue by RainbowHackerHorse** [chishm/nitrohax#3]
Golden Sun: Dark Dawn does not launch.
When launching it, a white screen appears and stays until you exit to the home screen.
it's an NTR game: NTR-B05E-USA
It's a fairly old game at this point, about 8 years since launch.
https://en.wikipedia.org/wiki/Golden_Sun:_Dark_Dawn

I am happy to test development builds to add support for this game.

**Comment by chishm** [comment]
I'll look into it. I've got a game card of it, so hopefully I can figure out what's wrong and fix it.

**Comment by chishm** [comment]
This has been fixed with commit 1dacaf200946ba478ee2228d046e9a29d102d7d3. The game boots, but I've noticed a little bit of flicker in the backgrounds. This is probably because NitroHax is hooking the VBlank interrupt, stealing execution time and resulting in the display not being updated quite fast enough.

Let me know if you need an .nds built, otherwise I'll just let this get picked up by NitroHax3DS.

**Comment by RainbowHackerHorse** [comment]
Dude, you rule.
I indeed am using the 3DS build, never owned an original.
Thanks so much for adding a fix, and so quickly! I saw so many posts on forums of people complaining that the game wasn't supported, but I seem to be the only person in years who thought to actually open an Issue, heh. Can't expect a programmer to know about a problem if no one tells them.
cheers!

**Comment by chishm** [comment]
Thanks :)

Since it sounds like there's some demand for GS:DD support (or at least there was), I've done a new release 0.93 of Nitro Hax. See https://www.chishm.com/NitroHax/index.html for download.

**Comment by RainbowHackerHorse** [comment]
Wicked sweet! Thank you on behalf of everyone who's rocking this game <3

The NitroHax3DS guys pushed out a .CIA with your new commit added as well, and I can confirm it works like a charm. Switching the timing via select in their build also eliminates that flickering problem, which is pretty darn cool :)
If you're ever in the SF area, I owe you a drink.

**Comment by bryben** [comment]
Hi, I would like to play Golden sun DD in my 3DS without R4 but when I launch the game in twilight menu, there are a white screen.. Somebody can help me?
