### ISSUE TITLE
Inazuma Eleven 2 Firestorm unsupported (probably?)

### ISSUE THREAD

**Issue by twlswan** [chishm/nitrohax#4]
So, after I choose the cheats and start the game, it freezes on a white screen. I tried making the cheats.xml smaller, but it still doesn't work.
I'd be very happy if u add support for this game! Thanks in advance!

**Comment by chishm** [comment]
Unfortunately I don't have a copy of that game to diagnose the issue properly. One thing to try is a cheats.xml with only the backlight code in it. If that doesn't work then the game is unsupported, for unknown reasons. Also make sure you're using the latest version of NitroHax (0.94) which introduced a fix for Golden Sun Dark Dawn that might apply to other games too.

Here's a cheat code that let's you adjust the backlight using L+R+Select+Up (or +Down) on a DS lite:
```
 94000130 fcfb0000
 c2000001 000000a0
 a21ab5f0 88234c24
 80138811 d02a428b
 25803490 f0002000
 1c06f82a f0002004
 2703f826 21404007
 d003420b 420b2180
 e018d00c 4231210c
 2f03d006 1c79d013
 f0002004 e00ef816
 e0094331 438e210c
 2f001c31 1e79d004
 f0002004 e002f80a
 f0002000 bcf0f806
 4718bc08 30800000
 88222100 d1fc422a
 80224a08 88208060
 d1fc4228 80220c12
 88228061 d1fc422a
 21ff8860 47704008
 04000130 80028802
 d2000000 00000000
```

**Comment by RadicalBean** [comment]
Updating to 0.94 fixes this: The maintainer of NitroHax3DS made a newer version you have to merge yourself, but he merged it anyways
https://mega.nz/#!WPoQiCaB!myQqYqMgaWSWcJXr-_oYTFPxEJBmunVIWg344wX1Dvs
https://github.com/ahezard/NitroHax3DS/issues/7

**Comment by chishm** [comment]
@RadicalBean Thank you for the confirmation of the fix. I'll close this issue as fixed.
