### ISSUE TITLE
XML files are not visible when cheats.xml file is not present

### ISSUE THREAD

**Issue by murrty1** [chishm/nitrohax#8]
It will not display any *.xml files, instead it will display files with any other extension.

I tried to bandaid fix it myself by replacing the ".xml" at

https://github.com/chishm/nitrohax/blob/329a37204a1b9fc2658993d5ce4f4ad64873231d/arm9/source/main.cpp#L76

with a dummy extension to show the file, but I am not able to get it to successfully build after hours of researching, so any other changes I could do I wouldn't be able to test.

Additional info, I'm running it off a R4i SDHC 3DS RTS with RetroGameFan's YSMenu

**Comment by chishm** [comment]
Thank you for the bug report.

I think I've fixed this, it was a one-line change. Do you mind testing [NitroHax](https://github.com/chishm/nitrohax/files/4141991/NitroHax.zip) with the fix?

**Comment by chishm** [comment]
Additionally, I've fixed up a few things so it should now build with the latest DevkitARM and libnds.

**Comment by murrty** [comment]
I built the bugfix branch, and it has fixed the problem. Thank you for fixing it up, building was easy peasy.

**Comment by murrty** [comment]
Ah, now the branch popped up the issue where it'll freeze when opening some folders. It seems to affect both the auto loaded file and the manually selected file, i'm gonna look more into it.

I did try the one that you linked above, same issue applied there. Although it's most likely an issue on my end by the looks of it.

**Comment by chishm** [comment]
Awesome, thanks for the confirmation. I'll merge the branch and close this ticket, and if there is a bug causing the freezing issue (or you can narrow it down to a test case) then please open a new ticket.
